### ISSUE TITLE
Implement VR Support

### ISSUE THREAD

**Issue by michalciurus** [benoit-dumas/DebugPlus#7]
Implement a canvas with world space that would attach to a camera.

I made it working by adding a couple of lines to `LogDrawer`. Thank you for this library, it's awesome :) Saved me a lot of time.

**Comment by methusalah** [comment]
Thanks, any way you can integrate your work in a pull request? The call could be:
DebugPlus.LogOnScreen("my message").Duration(t).Color(c).DrawInXR();
